### ISSUE TITLE
webpack_plugin.js:74:31: webpack is not defined

### ISSUE THREAD

**Issue by filipenevola** [ardatan/meteor-webpack#1]
Hello, thank you for your package :wink: it will be very nice to use webpack with Meteor.

I have a pretty standard React project with Meteor and I tried to follow the README steps but I got this error:
```
While processing files with ardatan:webpack (for target os.linux.x86_64):
   packages/webpack_plugin.js:74:31: webpack is not defined
   at Object.constructNewCompilerForTarget (packages/webpack_plugin.js:74:31)
   at Object.processFilesForTarget (packages/webpack_plugin.js:85:22)
```

Do you have any idea of what can be wrong on my code?

**Comment by ardatan** [comment]
Did you install webpack from npm?

**Comment by filipenevola** [comment]
Yes, I did globally and using the project's package.json (the recommended way).

**Comment by ardatan** [comment]
Could you try it to add webpack as dependency instead of devDependencies. Please let me know if there is any update

**Comment by filipenevola** [comment]
Maybe you need to add
```javascript
Npm.depends({
  webpack: '4.1.1'
});
```
to your package.js?

**Comment by ardatan** [comment]
Oh sorry, it is my mistake. I am using `webpack` as peerdependency in my package to make developers free to use any version of webpack with this atmosphere package. I think I published the old version of package, so I changed the version and re-published them.
Now you can check again by updating packages by `meteor update`.
Please let me know if anything changes.

**Comment by ardatan** [comment]
Could you run it successfully?
