### ISSUE TITLE
cannot find module 'webpack'

### ISSUE THREAD

**Issue by lauff** [ardatan/meteor-webpack#85]
I tried to run the react example from this repository, but Meteor exits with

=> Exited with code: 1
W20200213-15:27:10.232(0)? (STDERR) /root/.meteor/packages/meteor-tool/.1.8.1.1a5ebbe.mcw0j++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20200213-15:27:10.233(0)? (STDERR)                                             throw(ex);
W20200213-15:27:10.237(0)? (STDERR)                                             ^
W20200213-15:27:10.238(0)? (STDERR)
W20200213-15:27:10.238(0)? (STDERR) Error: Cannot find module 'webpack'
W20200213-15:27:10.238(0)? (STDERR)     at Function.Module._resolveFilename (module.js:548:15)
W20200213-15:27:10.239(0)? (STDERR)     at Function.Module._load (module.js:475:25)
W20200213-15:27:10.239(0)? (STDERR)     at Module.require (module.js:597:17)
W20200213-15:27:10.239(0)? (STDERR)     at require (internal/module.js:11:18)
W20200213-15:27:10.240(0)? (STDERR)     at Object.<anonymous> (/app/webpack.config.js:1:17)
W20200213-15:27:10.240(0)? (STDERR)     at Module._compile (module.js:653:30)
W20200213-15:27:10.240(0)? (STDERR)     at Object.Module._extensions..js (module.js:664:10)
W20200213-15:27:10.241(0)? (STDERR)     at Module.load (module.js:566:32)
W20200213-15:27:10.241(0)? (STDERR)     at tryModuleLoad (module.js:506:12)
W20200213-15:27:10.241(0)? (STDERR)     at Function.Module._load (module.js:498:3)
W20200213-15:27:10.242(0)? (STDERR)     at Module.require (module.js:597:17)
W20200213-15:27:10.249(0)? (STDERR)     at require (internal/module.js:11:18)
W20200213-15:27:10.250(0)? (STDERR)     at Object.require (/app2/.meteor/local/build/programs/server/boot.js:292:20)
W20200213-15:27:10.250(0)? (STDERR)     at packages/ardatan_webpack-dev-middleware.js:252:45
W20200213-15:27:10.250(0)? (STDERR)     at packages/ardatan_webpack-dev-middleware.js:386:4
W20200213-15:27:10.250(0)? (STDERR)     at packages/ardatan_webpack-dev-middleware.js:392:3

**Comment by lauff** [comment]
no idea why - but it is working now...

**Comment by lauff** [comment]
strange, now I get the error again - using the same project on different PCs
