### ISSUE TITLE
error run meteor after upgrade from 1.8.0.1 to 1.9

### ISSUE THREAD

**Issue by moslemir** [ardatan/meteor-webpack#86]
my error:
`
E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected token < in JSON at position 109
    at JSON.parse (<anonymous>)
    at E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\fs\tools\fs\optimistic.ts:321:17
    at wrap.makeCacheKey (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\fs\tools\fs\optimistic.ts:36:15)
    at recomputeNewValue (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\src\entry.ts:182:31)
    at Slot.withValue (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\@wry\context\lib\context.js:73:29)
    at reallyRecompute (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\src\entry.ts:165:19)
    at Entry.recompute (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\src\entry.ts:85:9)
    at optimistic (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\src\index.ts:101:25)
    at E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\fs\tools\fs\optimistic.ts:366:19
    at recomputeNewValue (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\src\entry.ts:182:31)
    at Slot.withValue (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\@wry\context\lib\context.js:73:29)
    at reallyRecompute (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\src\entry.ts:165:19)
    at Entry.recompute (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\src\entry.ts:85:9)
    at optimistic (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\src\index.ts:101:25)
    at find (E:\tools\isobuild\package-source.js:1292:30)
    at E:\tools\isobuild\package-source.js:1345:27
    at Array.forEach (<anonymous>)
    at find (E:\tools\isobuild\package-source.js:1324:22)
    at E:\tools\isobuild\package-source.js:1345:27
    at Array.forEach (<anonymous>)
    at find (E:\tools\isobuild\package-source.js:1324:22)
    at E:\tools\isobuild\package-source.js:1345:27
    at Array.forEach (<anonymous>)
    at find (E:\tools\isobuild\package-source.js:1324:22)
    at E:\tools\isobuild\package-source.js:1345:27
    at Array.forEach (<anonymous>)
    at find (E:\tools\isobuild\package-source.js:1324:22)
    at find (E:\tools\isobuild\package-source.js:1356:25)
    at E:\tools\isobuild\package-source.js:1368:34
    at Object.withCache (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1650:18)
    at PackageSource._findSources (E:\tools\isobuild\package-source.js:1368:18)
    at SourceArch.getFiles (E:\tools\isobuild\package-source.js:916:32)
    at E:\tools\isobuild\compiler.js:406:23
    at E:\tools\isobuild\compiler.js:186:28
    at Object.withCache (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1650:18)
    at E:\tools\isobuild\compiler.js:185:11
    at Function._.each._.forEach (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:186:9)
    at Object.compile (E:\tools\isobuild\compiler.js:180:5)
    at E:\tools\isobuild\bundler.js:3217:24
    at Object.capture (E:\tools\utils\buildmessage.js:283:5)
    at bundle (E:\tools\isobuild\bundler.js:3164:31)
    at E:\tools\isobuild\bundler.js:3109:32
    at Slot.withValue (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\@wry\context\lib\context.js:73:29)
    at Object.withCache (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1650:39)
    at Object.bundle (E:\tools\isobuild\bundler.js:3109:16)
    at E:\tools\runners\run-app.js:572:24
    at Function.run (E:\Meteor\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:289:14)
    at bundleApp (E:\tools\runners\run-app.js:571:34)
    at AppRunner._runOnce (E:\tools\runners\run-app.js:613:35)
    at AppRunner._fiber (E:\tools\runners\run-app.js:919:28)
    at E:\tools\runners\run-app.js:401:12
error Command failed with exit code 1.`

my package file: 
`meteor-base@1.4.0
mongo@1.8.0
tracker@1.2.0
shell-server
aldeed:collection2
accounts-password@1.5.2
ardatan:webpack
ardatan:webpack-dev-middleware`

my versions file:
`accounts-base@1.5.0
accounts-password@1.5.3
aldeed:collection2@3.0.6
allow-deny@1.1.0
ardatan:webpack@0.0.13
ardatan:webpack-dev-middleware@0.0.13
autoupdate@1.6.0
babel-compiler@7.5.2
babel-runtime@1.5.0
base64@1.0.12
binary-heap@1.0.11
boilerplate-generator@1.6.0
callback-hook@1.3.0
check@1.3.1
ddp@1.4.0
ddp-client@2.3.3
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.3.1
diff-sequence@1.1.1
dynamic-import@0.5.1
ecmascript@0.14.2
ecmascript-runtime@0.7.0
ecmascript-runtime-client@0.10.0
ecmascript-runtime-server@0.9.0
ejson@1.1.1
email@1.2.3
es5-shim@4.8.0
fetch@0.1.1
geojson-utils@1.0.10
hot-code-push@1.0.4
id-map@1.1.0
inter-process-messaging@0.1.0
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
meteor@1.9.3
meteor-base@1.4.0
minimongo@1.4.5
modern-browsers@0.1.5
modules@0.15.0
modules-runtime@0.12.0
mongo@1.8.1
mongo-decimal@0.1.1
mongo-dev-server@1.1.0
mongo-id@1.0.7
npm-bcrypt@0.9.3
npm-mongo@3.3.0
ordered-dict@1.1.0
promise@0.11.2
raix:eventemitter@1.0.0
random@1.1.0
rate-limit@1.0.9
reactive-var@1.0.11
reload@1.3.0
retry@1.1.0
routepolicy@1.1.0
service-configuration@1.0.11
sha@1.0.9
shell-server@0.4.0
socket-stream-client@0.2.3
srp@1.0.12
tmeasday:check-npm-versions@0.3.2
tracker@1.2.0
underscore@1.0.10
webapp@1.8.2
webapp-hashing@1.0.9
`

**Comment by moslemir** [comment]
@ardatan
